# Settings
baseurl: 
permalink: /:categories/:title

# About
title: BTS SIO
tagline: Module SLAM5
authors:
  - name: Baptiste Pesquet
    url: 'http://bpesquet.fr'
created: 
license:
  name: Creative Commons BY-NC-SA 4.0
  shortname: CC BY-NC-SA 4.0
  url: http://creativecommons.org/licenses/by-nc-sa/4.0/
  badge: http://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png
  
# Collections
collections:
  addons:
    output: true
    permalink: /:collection/:path:output_ext

# Default values
defaults:
  - scope:
      path: ''
    values:
      addons:
        highlightjs: yes
        print-link: yes
        about: yes

kramdown:
  parse_block_html: true
